version: '3.9'
x-common-variables: &common-variables
  ASPNETCORE_ENVIRONMENT: Development

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgres/
    networks:
      - todo-app-network

  product-api:
    image: ${DOCKER_REGISTRY-}product-api
    container_name: product-api
    build:
      context: .
      dockerfile: src/Product/TodoApp.Product.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5001
      - ApplicationName=product-api
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ProductDbContext=Host=postgres;Database=TodoAppProduct;Username=postgres;Password=1;Port=5432
      - RabbitMQ__Host=rabitmq
    ports:
      - "5001:5001"
    restart: always
    networks:
      - todo-app-network
  order-api:
    image: ${DOCKER_REGISTRY-}order-api
    container_name: order-api
    build:
      context: .
      dockerfile: src/Order/TodoApp.Order.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5002
      - ApplicationName=order-api
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__OrderDbContext=Host=postgres;Database=TodoAppOrder;Username=postgres;Password=1;Port=5432
      - RabbitMQ__Host=rabitmq
    ports:
      - "5002:5002"
    restart: always
    networks:
      - todo-app-network


  ############################
  # Zipkin component
  ############################
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - todo-app-network

  collector:
    container_name: collector
    image: otel/opentelemetry-collector-contrib:0.78.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
    depends_on:
      - zipkin

  ############################
  # Redis state store
  ############################
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - todo-app-network

  rabbitmq:
    image: rabbitmq:3.10.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - todo-app-network

volumes:
  postgres-data:
    external: false
  grafana-data:
    external: false
networks:
  todo-app-network:
    driver: bridge