version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=postgres
    ports:
      - 55432:5432
    volumes:
      - postgres-data:/var/lib/postgres/
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.10.7-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
    restart: always
  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    build: 
      context: .
      dockerfile: src/Product/TodoApp.Product.API/Dockerfile
volumes:
  rabbitmq-data:
    external: false
  postgres-data:
    external: false