receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
  filter:
    spans:
      exclude:
        match_type: strict
        span_names:
          - /swagger/v1/swagger.json
          - /swagger/index.html

exporters:
  zipkin:
    endpoint: "0.0.0.0:9411/api/v2/spans"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, filter]
      exporters: [zipkin]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [zipkin]