apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: productpubsub
spec:
  # type: pubsub.rabbitmq
  # version: v1
  # metadata:
  # - name: connectionString
  #   value: amqp://guest:guest@localhost:5672
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis:6379
  - name: redisPassword
    value: ""